# Generated by Django 4.1.2 on 2022-10-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='box',
            new_name='nivel',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='answer',
            new_name='pergunta',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='question',
            new_name='resposta',
        ),
    ]
